import streamlit as st
import pandas as pd
import io
import os
import uuid
from datetime import date, datetime, timedelta
import database as db
import styles
import plotly.graph_objects as go
import plotly.express as px

# ============================================
# SESSION STATE INITIALIZATION
# ============================================

def init_session_state():
    if 'expense_photo_cache' not in st.session_state:
        st.session_state.expense_photo_cache = {}
    if 'expense_edit_id' not in st.session_state:
        st.session_state.expense_edit_id = None

init_session_state()

# ============================================
# HELPERS
# ============================================

EXPENSE_CATEGORIES = [
    "Equipment",
    "Maintenance",
    "Utilities",
    "Salaries",
    "Marketing",
    "Rent",
    "Supplies",
    "Cleaning",
    "Other"
]

PAYMENT_METHODS = ["Cash", "Bank Transfer", "Credit Card", "Debit Card", "Mobile Payment", "Cheque"]

def get_expense_status(expense):
    """Get status of expense"""
    if not expense or not hasattr(expense, 'expense_date'):
        return "pending", "⏳ Pending", "#F59E0B"
    
    try:
        expense_date = pd.to_datetime(expense.expense_date).date()
        today = date.today()
        
        if expense_date <= today:
            return "paid", "✅ Paid", "#10B981"
        else:
            return "upcoming", "🟡 Upcoming", "#F59E0B"
    except:
        return "pending", "⏳ Pending", "#F59E0B"

def generate_expense_report(expenses, gym_name):
    """Generate professional expense report"""
    if not expenses:
        return "No expenses found."
    
    total = sum(e.amount for e in expenses)
    
    report = f"""
📊 EXPENSE REPORT - {gym_name}
📅 Generated: {date.today().strftime('%B %d, %Y')}
{'='*50}

💰 TOTAL EXPENSES: PKR {total:,.2f}
📋 Total Records: {len(expenses)}

📂 CATEGORY BREAKDOWN:
"""
    
    # Category breakdown
    category_totals = {}
    for e in expenses:
        cat = e.category or "Uncategorized"
        category_totals[cat] = category_totals.get(cat, 0) + e.amount
    
    for cat, amt in sorted(category_totals.items(), key=lambda x: x[1], reverse=True):
        percentage = (amt / total * 100) if total > 0 else 0
        report += f"  • {cat}: PKR {amt:,.2f} ({percentage:.1f}%)\n"
    
    report += f"""
{'='*50}
📅 DATE RANGE:
  • From: {min(e.expense_date for e in expenses) if expenses else 'N/A'}
  • To: {max(e.expense_date for e in expenses) if expenses else 'N/A'}

👤 STAFF:
"""
    
    # Staff breakdown
    staff_totals = {}
    for e in expenses:
        staff = e.staff_name or "Unknown"
        staff_totals[staff] = staff_totals.get(staff, 0) + e.amount
    
    for staff, amt in staff_totals.items():
        report += f"  • {staff}: PKR {amt:,.2f}\n"
    
    report += f"""
{'='*50}
📱 Generated by GymPro - Multi-Gym Management
"""
    
    return report

# ============================================
# MAIN RENDER FUNCTION
# ============================================

def render(gym_id, role, current_user):
    
    # ============================================
    # 3D CSS STYLES
    # ============================================
    
    st.markdown("""
    <style>
        /* 3D Card Effect */
        .card-3d {
            background: linear-gradient(145deg, #1E293B, #0F172A);
            border: 1px solid #334155;
            border-radius: 16px;
            padding: 1.5rem;
            box-shadow: 
                0 10px 30px rgba(0,0,0,0.5),
                0 4px 10px rgba(0,0,0,0.3),
                inset 0 -2px 0 rgba(255,255,255,0.05);
            transition: all 0.3s ease;
            position: relative;
            overflow: hidden;
        }
        
        .card-3d:hover {
            transform: translateY(-5px);
            box-shadow: 
                0 20px 40px rgba(0,0,0,0.6),
                0 8px 20px rgba(0,0,0,0.4),
                inset 0 -2px 0 rgba(255,255,255,0.08);
        }
        
        .card-3d::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 3px;
            background: linear-gradient(90deg, #7C3AED, #A78BFA, #7C3AED);
            box-shadow: 0 0 20px rgba(124,58,237,0.3);
        }
        
        .card-3d .icon {
            font-size: 2.5rem;
            margin-bottom: 0.5rem;
            display: block;
        }
        
        .card-3d .value {
            font-size: 2rem;
            font-weight: 800;
            color: #F8FAFC;
            text-shadow: 0 2px 10px rgba(0,0,0,0.3);
        }
        
        .card-3d .label {
            font-size: 0.8rem;
            color: #94A3B8;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            font-weight: 600;
        }
        
        .card-3d.glow-purple {
            border-color: rgba(124,58,237,0.3);
        }
        
        .card-3d.glow-green {
            border-color: rgba(52,211,153,0.3);
        }
        
        .card-3d.glow-red {
            border-color: rgba(248,113,113,0.3);
        }
        
        .card-3d.glow-yellow {
            border-color: rgba(251,191,36,0.3);
        }
        
        .card-3d.glow-blue {
            border-color: rgba(96,165,250,0.3);
        }
        
        /* 3D Button Effect */
        .btn-3d {
            background: linear-gradient(145deg, #7C3AED, #6D28D9);
            border: none;
            border-radius: 10px;
            padding: 0.7rem 1.5rem;
            color: white;
            font-weight: 700;
            font-size: 0.9rem;
            cursor: pointer;
            transition: all 0.3s ease;
            box-shadow: 
                0 6px 20px rgba(124,58,237,0.4),
                inset 0 -3px 0 rgba(0,0,0,0.2);
            text-align: center;
            display: inline-block;
            width: 100%;
        }
        
        .btn-3d:hover {
            transform: translateY(-3px);
            box-shadow: 
                0 10px 30px rgba(124,58,237,0.5),
                inset 0 -3px 0 rgba(0,0,0,0.2);
        }
        
        .btn-3d:active {
            transform: translateY(0px);
            box-shadow: 
                0 4px 15px rgba(124,58,237,0.3),
                inset 0 -3px 0 rgba(0,0,0,0.2);
        }
    </style>
    """, unsafe_allow_html=True)
    
    # ============================================
    # HEADER
    # ============================================
    
    styles.page_header("💰", "Expenditure Management", "Track, manage, and analyze all gym expenses")
    
    gyms = db.get_all_gyms()
    if not gyms:
        st.info("🏋️ Add a gym first to start tracking expenses.")
        return

    # ============================================
    # SELECTION
    # ============================================
    
    st.markdown("""
    <div style="background:linear-gradient(145deg,#1E293B,#0F172A);
                border:1px solid #334155;
                border-radius:12px;
                padding:1rem;
                margin-bottom:1rem;
                box-shadow:0 4px 15px rgba(0,0,0,0.3);">
    """, unsafe_allow_html=True)
    
    col_sel1, col_sel2 = st.columns(2)
    
    with col_sel1:
        if gym_id:
            sel_gid = gym_id
            st.text_input("🏋️ Gym", value=next((g.name for g in gyms if g.id == gym_id), ""), disabled=True)
        else:
            opts = {"All Gyms": None} | {g.name: g.id for g in gyms}
            chosen = st.selectbox("🏋️ Gym", list(opts.keys()))
            sel_gid = opts[chosen]
    
    with col_sel2:
        st.write("")
        st.write("")
        if st.button("🔄 Refresh Data", use_container_width=True):
            st.rerun()
    
    st.markdown("</div>", unsafe_allow_html=True)

    # ============================================
    # GET DATA
    # ============================================
    
    expenses = db.get_expenses(gym_id=sel_gid)
    
    # Calculate totals
    total_expenses = sum(e.amount for e in expenses) if expenses else 0
    total_records = len(expenses)
    
    # Monthly expenses
    today = date.today()
    current_month = today.month
    current_year = today.year
    monthly_expenses = sum(e.amount for e in expenses if e.expense_date and 
                          pd.to_datetime(e.expense_date).month == current_month and
                          pd.to_datetime(e.expense_date).year == current_year) if expenses else 0
    
    # Count by category
    category_counts = {}
    for e in expenses:
        cat = e.category or "Uncategorized"
        category_counts[cat] = category_counts.get(cat, 0) + 1
    
    # Most common category
    most_common = max(category_counts.items(), key=lambda x: x[1])[0] if category_counts else "—"

    # ============================================
    # STATS CARDS (3D)
    # ============================================
    
    col1, col2, col3, col4, col5 = st.columns(5)
    
    with col1:
        st.markdown(f"""
        <div class="card-3d glow-purple" style="text-align:center;">
            <span class="icon">💰</span>
            <div class="value">PKR {total_expenses:,.0f}</div>
            <div class="label">Total Expenses</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col2:
        st.markdown(f"""
        <div class="card-3d glow-green" style="text-align:center;">
            <span class="icon">📋</span>
            <div class="value">{total_records}</div>
            <div class="label">Total Records</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col3:
        st.markdown(f"""
        <div class="card-3d glow-yellow" style="text-align:center;">
            <span class="icon">📅</span>
            <div class="value">PKR {monthly_expenses:,.0f}</div>
            <div class="label">This Month</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col4:
        avg_expense = (total_expenses / total_records) if total_records > 0 else 0
        st.markdown(f"""
        <div class="card-3d glow-blue" style="text-align:center;">
            <span class="icon">📊</span>
            <div class="value">PKR {avg_expense:,.0f}</div>
            <div class="label">Average per Record</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col5:
        st.markdown(f"""
        <div class="card-3d glow-red" style="text-align:center;">
            <span class="icon">🏷️</span>
            <div class="value" style="font-size:1.2rem;">{most_common}</div>
            <div class="label">Most Common Category</div>
        </div>
        """, unsafe_allow_html=True)

    # ============================================
    # TABS
    # ============================================
    
    tab_add, tab_view, tab_analytics = st.tabs([
        "📝 Add Expense",
        "📋 View All Expenses",
        "📊 Analytics & Reports"
    ])

    # ============================================
    # TAB 1: ADD EXPENSE (DATABASE COMPATIBLE)
    # ============================================
    
    with tab_add:
        st.markdown("""
        <div style="background:linear-gradient(145deg,#1E293B,#0F172A);
                    border:1px solid #334155;
                    border-radius:12px;
                    padding:1.5rem;
                    box-shadow:0 8px 25px rgba(0,0,0,0.3);">
        """, unsafe_allow_html=True)
        
        with st.form("add_expense_form", clear_on_submit=True):
            col_a1, col_a2 = st.columns(2)
            
            with col_a1:
                expense_category = st.selectbox("📂 Category *", EXPENSE_CATEGORIES)
                amount = st.number_input("💰 Amount (PKR) *", min_value=0.01, step=10.0, format="%.2f")
                expense_date = st.date_input("📅 Expense Date *", value=date.today())
            
            with col_a2:
                staff_name = st.text_input("👤 Staff Name (optional)", placeholder="Who recorded this expense?")
                description = st.text_area("📝 Description (optional)", height=80, placeholder="Brief description of expense...")
            
            col_btn1, col_btn2, col_btn3 = st.columns([2, 1, 1])
            with col_btn1:
                submitted = st.form_submit_button(
                    "💾 Add Expense",
                    type="primary",
                    use_container_width=True
                )
            with col_btn2:
                if st.form_submit_button("🔄 Reset", use_container_width=True):
                    st.rerun()
            
            if submitted:
                if amount <= 0:
                    st.error("❌ Amount must be greater than 0!")
                else:
                    # ✅ DATABASE COMPATIBLE - Using correct parameters
                    ok, msg = db.add_expense(
                        gym_id=sel_gid,
                        amount=amount,
                        category=expense_category,
                        description=description,
                        expense_date=expense_date,
                        staff_name=staff_name
                    )
                    if ok:
                        st.success(f"✅ {msg}")
                        st.balloons()
                        st.rerun()
                    else:
                        st.error(f"❌ {msg}")
        
        st.markdown("</div>", unsafe_allow_html=True)

    # ============================================
    # TAB 2: VIEW ALL EXPENSES
    # ============================================
    
    with tab_view:
        st.markdown("""
        <div style="background:linear-gradient(145deg,#1E293B,#0F172A);
                    border:1px solid #334155;
                    border-radius:12px;
                    padding:1.5rem;
                    box-shadow:0 8px 25px rgba(0,0,0,0.3);">
        """, unsafe_allow_html=True)
        
        # Filters
        col_f1, col_f2, col_f3, col_f4 = st.columns([2, 1.5, 1.5, 1])
        
        with col_f1:
            category_filter = st.selectbox("📂 Category", ["All"] + EXPENSE_CATEGORIES, key="cat_filter")
        with col_f2:
            date_from = st.date_input("📅 From", value=date.today().replace(day=1), key="exp_from")
        with col_f3:
            date_to = st.date_input("📅 To", value=date.today(), key="exp_to")
        with col_f4:
            st.write("")
            st.write("")
            if st.button("🔄 Apply", use_container_width=True):
                st.rerun()
        
        # Filter expenses
        filtered_expenses = expenses
        if category_filter != "All":
            filtered_expenses = [e for e in filtered_expenses if e.category == category_filter]
        if date_from:
            filtered_expenses = [e for e in filtered_expenses if e.expense_date and pd.to_datetime(e.expense_date).date() >= date_from]
        if date_to:
            filtered_expenses = [e for e in filtered_expenses if e.expense_date and pd.to_datetime(e.expense_date).date() <= date_to]
        
        # Show filtered count
        st.caption(f"📋 Showing {len(filtered_expenses)} expense(s)")
        
        if filtered_expenses:
            # Prepare data for display
            display_data = []
            for e in filtered_expenses:
                status_type, status_text, status_color = get_expense_status(e)
                display_data.append({
                    "ID": e.id,
                    "Date": e.expense_date,
                    "Category": e.category,
                    "Amount": e.amount,
                    "Description": e.description or "—",
                    "Staff": e.staff_name or "—",
                    "Status": status_text,
                    "Status Color": status_color,
                })
            
            df = pd.DataFrame(display_data)
            df["Amount"] = df["Amount"].apply(lambda x: f"PKR {x:,.2f}")
            
            # Display table
            st.dataframe(
                df[["Date", "Category", "Amount", "Description", "Staff", "Status"]],
                use_container_width=True,
                hide_index=True,
                height=400,
                column_config={
                    "Date": st.column_config.DateColumn("Date", width="small"),
                    "Category": st.column_config.TextColumn("Category", width="medium"),
                    "Amount": st.column_config.TextColumn("Amount", width="small"),
                    "Description": st.column_config.TextColumn("Description", width="medium"),
                    "Staff": st.column_config.TextColumn("Staff", width="small"),
                    "Status": st.column_config.TextColumn("Status", width="small"),
                }
            )
            
            # Total
            total_filtered = sum(e.amount for e in filtered_expenses)
            st.markdown(f"""
            <div style="background:#0F172A;border:1px solid #334155;border-radius:8px;padding:0.8rem;text-align:center;margin-top:0.5rem;">
                <span style="color:#94A3B8;">Total Amount: </span>
                <span style="color:#34D399;font-weight:700;font-size:1.2rem;">PKR {total_filtered:,.2f}</span>
            </div>
            """, unsafe_allow_html=True)
            
            # Export
            col_exp1, col_exp2, col_exp3 = st.columns([1, 1, 3])
            with col_exp1:
                if st.button("⬇️ Export CSV", use_container_width=True):
                    csv_buf = io.StringIO()
                    df.to_csv(csv_buf, index=False)
                    st.download_button(
                        "📥 Download", 
                        data=csv_buf.getvalue().encode(), 
                        file_name=f"expenses_{date.today()}.csv", 
                        mime="text/csv",
                        use_container_width=True
                    )
            
            with col_exp2:
                if st.button("📋 Copy Report", use_container_width=True):
                    gym_name = next((g.name for g in gyms if g.id == sel_gid), "GymPro") if sel_gid else "All Gyms"
                    report = generate_expense_report(filtered_expenses, gym_name)
                    st.code(report, language="text")
                    st.success("✅ Report copied below!")
            
            # Admin Actions
            if str(role).lower() in ["admin", "owner"]:
                st.divider()
                st.subheader("🔐 Admin Actions")
                st.caption("Edit or delete expense records")
                
                # Select record
                record_opts = {f"{e.expense_date} - {e.category} (PKR {e.amount:,.2f})": e.id for e in filtered_expenses}
                selected_label = st.selectbox("Select Record to Manage", list(record_opts.keys()), key="exp_admin_select")
                selected_id = record_opts[selected_label]
                
                col_edit, col_delete = st.columns(2)
                
                # Edit
                with col_edit:
                    with st.expander("✏️ Edit Record", expanded=False):
                        selected_exp = next((e for e in filtered_expenses if e.id == selected_id), None)
                        if selected_exp:
                            with st.form("edit_expense_form"):
                                new_category = st.selectbox("Category", EXPENSE_CATEGORIES, index=EXPENSE_CATEGORIES.index(selected_exp.category) if selected_exp.category in EXPENSE_CATEGORIES else 0)
                                new_amount = st.number_input("Amount (PKR)", min_value=0.01, value=float(selected_exp.amount), step=10.0, format="%.2f")
                                new_date = st.date_input("Expense Date", value=pd.to_datetime(selected_exp.expense_date).date() if selected_exp.expense_date else date.today())
                                new_description = st.text_area("Description", value=selected_exp.description or "")
                                new_staff = st.text_input("Staff Name", value=selected_exp.staff_name or "")
                                
                                if st.form_submit_button("💾 Save Changes", type="primary", use_container_width=True):
                                    # Note: update_expense may not exist in database, so we'll just show a message
                                    st.warning("⚠️ Edit functionality requires update_expense in database.py")
                                    st.info(f"Would update: {selected_exp.id} with {new_category} - PKR {new_amount}")
                # Delete
                with col_delete:
                    with st.expander("🗑️ Delete Record", expanded=False):
                        st.warning(f"⚠️ Delete this expense record?")
                        st.caption("This cannot be undone!")
                        if st.button("🚨 Confirm Delete", type="primary", use_container_width=True):
                            if hasattr(db, 'delete_expense'):
                                ok, msg = db.delete_expense(selected_id)
                                if ok:
                                    st.success("✅ Record deleted!")
                                    st.rerun()
                                else:
                                    st.error(msg)
                            else:
                                st.error("⚠️ Delete function not available")
        else:
            st.info("📭 No expenses found for the selected filters.")
        
        st.markdown("</div>", unsafe_allow_html=True)

    # ============================================
    # TAB 3: ANALYTICS & REPORTS
    # ============================================
    
    with tab_analytics:
        st.markdown("""
        <div style="background:linear-gradient(145deg,#1E293B,#0F172A);
                    border:1px solid #334155;
                    border-radius:12px;
                    padding:1.5rem;
                    box-shadow:0 8px 25px rgba(0,0,0,0.3);">
        """, unsafe_allow_html=True)
        
        if not expenses:
            st.info("📊 No data available for analytics. Add some expenses first!")
        else:
            # Category breakdown chart
            st.subheader("📊 Category Breakdown")
            
            category_totals = {}
            for e in expenses:
                cat = e.category or "Uncategorized"
                category_totals[cat] = category_totals.get(cat, 0) + e.amount
            
            if category_totals:
                # Create pie chart
                fig = go.Figure(data=[go.Pie(
                    labels=list(category_totals.keys()),
                    values=list(category_totals.values()),
                    hole=0.4,
                    marker=dict(colors=['#7C3AED', '#34D399', '#FBBF24', '#F87171', '#60A5FA', '#F472B6', '#34D399', '#F59E0B']),
                    textinfo='label+percent',
                    textposition='auto',
                    hoverinfo='label+value+percent',
                )])
                
                fig.update_layout(
                    template='plotly_dark',
                    title=dict(text="Expenses by Category", font=dict(color='#F8FAFC', size=20)),
                    plot_bgcolor='#0F172A',
                    paper_bgcolor='#0F172A',
                    height=450,
                    margin=dict(l=40, r=40, t=60, b=40),
                    showlegend=False,
                )
                
                st.plotly_chart(fig, use_container_width=True)
            
            # Monthly trend
            st.subheader("📈 Monthly Trend")
            
            # Group by month
            monthly_data = {}
            for e in expenses:
                if e.expense_date:
                    month_key = pd.to_datetime(e.expense_date).strftime("%b %Y")
                    monthly_data[month_key] = monthly_data.get(month_key, 0) + e.amount
            
            if monthly_data:
                # Sort by date
                sorted_months = sorted(monthly_data.keys(), key=lambda x: datetime.strptime(x, "%b %Y"))
                sorted_values = [monthly_data[m] for m in sorted_months]
                
                fig = go.Figure(data=[
                    go.Bar(
                        x=sorted_months,
                        y=sorted_values,
                        marker_color='#7C3AED',
                        marker_line_color='#A78BFA',
                        marker_line_width=1,
                        hovertemplate='Month: %{x}<br>Total: PKR %{y:,.2f}<extra></extra>'
                    )
                ])
                
                fig.update_layout(
                    template='plotly_dark',
                    title=dict(text="Monthly Expenses", font=dict(color='#F8FAFC', size=20)),
                    xaxis=dict(title="Month", gridcolor='#1E293B'),
                    yaxis=dict(title="Amount (PKR)", gridcolor='#1E293B'),
                    plot_bgcolor='#0F172A',
                    paper_bgcolor='#0F172A',
                    height=400,
                    margin=dict(l=40, r=40, t=60, b=40),
                )
                
                st.plotly_chart(fig, use_container_width=True)
            
            # Staff breakdown
            st.subheader("👤 Staff Expenses")
            
            staff_totals = {}
            for e in expenses:
                staff = e.staff_name or "Unknown"
                staff_totals[staff] = staff_totals.get(staff, 0) + e.amount
            
            if staff_totals:
                col_m1, col_m2 = st.columns([2, 1])
                
                with col_m1:
                    fig = go.Figure(data=[go.Pie(
                        labels=list(staff_totals.keys()),
                        values=list(staff_totals.values()),
                        marker=dict(colors=['#7C3AED', '#34D399', '#FBBF24', '#F87171', '#60A5FA']),
                        textinfo='label+percent',
                        textposition='auto',
                    )])
                    
                    fig.update_layout(
                        template='plotly_dark',
                        title=dict(text="Staff Expenses", font=dict(color='#F8FAFC', size=16)),
                        plot_bgcolor='#0F172A',
                        paper_bgcolor='#0F172A',
                        height=350,
                        margin=dict(l=20, r=20, t=40, b=20),
                    )
                    
                    st.plotly_chart(fig, use_container_width=True)
                
                with col_m2:
                    st.markdown("**👤 Staff Totals:**")
                    for staff, amt in sorted(staff_totals.items(), key=lambda x: x[1], reverse=True):
                        st.markdown(f"• {staff}: **PKR {amt:,.2f}**")
            
            # Quick Stats
            st.subheader("📊 Quick Stats")
            
            col_s1, col_s2, col_s3 = st.columns(3)
            with col_s1:
                st.metric("🏷️ Most Common", most_common)
            with col_s2:
                avg_exp = total_expenses / total_records if total_records > 0 else 0
                st.metric("📈 Avg per Record", f"PKR {avg_exp:,.2f}")
            with col_s3:
                if expenses and any(e.expense_date for e in expenses):
                    first_date = pd.to_datetime(min(e.expense_date for e in expenses if e.expense_date)).date()
                    days = (date.today() - first_date).days
                    st.metric("📅 Tracking Days", days)
                else:
                    st.metric("📅 Tracking Days", 0)
        
        st.markdown("</div>", unsafe_allow_html=True)